import 'package:flutter/material.dart';

class TermsConditionsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Terms and Conditions'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: RichText(
            text: TextSpan(
              style: TextStyle(fontSize: 16, color: Colors.black),
              children: [
                TextSpan(
                  text: 'Terms and Conditions\n\n',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'Welcome to ',
                ),
                TextSpan(
                  text: 'Youv.ai',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' ("App", "we", "our", "us"). By accessing or using our App, you ("user", "you", "your") agree to be bound by these Terms and Conditions. Please read them carefully. If you do not agree, you should not use the App.\n\n',
                ),
                TextSpan(
                  text: '1. Purpose of the App\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'The ',
                ),
                TextSpan(
                  text: 'Youv.ai App',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' provides ',
                ),
                TextSpan(
                  text: 'AI-based skin analysis',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' and related insights for ',
                ),
                TextSpan(
                  text: 'educational and informational purposes only',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: '.\n\nThe results, images, or recommendations generated are ',
                ),
                TextSpan(
                  text: 'not medical advice, diagnosis, or treatment',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: '.\n\nAlways consult a licensed dermatologist or healthcare professional for any medical concerns.\n\n',
                ),
                TextSpan(
                  text: '2. Eligibility\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'You must be at least ',
                ),
                TextSpan(
                  text: '18 years old',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' (or have parental/guardian consent if under 18) to use the App.\n\nBy using the App, you confirm that all information you provide is accurate and truthful.\n\n',
                ),
                TextSpan(
                  text: '3. Use of AI-Generated Content\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'All ',
                ),
                TextSpan(
                  text: 'analysis, reports, and visual outputs',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' (including "before/after" simulations) are generated by AI and may not fully reflect actual results.\n\nThe App ',
                ),
                TextSpan(
                  text: 'does not guarantee accuracy',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' of the analysis or results.\n\nAI-generated outputs should not be considered a substitute for professional medical consultation.\n\n',
                ),
                TextSpan(
                  text: '4. User Responsibilities\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'By using the App, you agree:\n\nTo use the App for personal and non-commercial purposes only.\n\nNot to misuse, copy, or resell AI outputs without our written consent.\n\nTo upload only your own images (or images you have the legal right to use).\n\nNot to upload offensive, unlawful, or harmful content.\n\n',
                ),
                TextSpan(
                  text: '5. Privacy & Data Usage\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'We may collect and process personal data (including images) for the purpose of providing AI skin analysis.\n\nUploaded images may be temporarily stored and processed by our AI system.\n\nWe do not sell your personal information to third parties.\n\nPlease review our ',
                ),
                TextSpan(
                  text: 'Privacy Policy',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' for more details on how we handle data.\n\n',
                ),
                TextSpan(
                  text: '6. Payments & Subscriptions (If Applicable)\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'Some features may require a subscription or one-time payment.\n\nAll applicable fees are displayed in the App before purchase.\n\nPayments are processed securely through trusted third-party payment providers.\n\n',
                ),
                TextSpan(
                  text: '7. Disclaimers\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'The App and its AI features are provided ',
                ),
                TextSpan(
                  text: '"as is" and "as available"',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ', without any warranties of any kind.\n\nWe make no guarantees about the accuracy, reliability, or outcomes of using the App.\n\nWe are not responsible for any decisions or actions you take based on AI outputs.\n\n',
                ),
                TextSpan(
                  text: '8. Limitation of Liability\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'To the maximum extent permitted by law, ',
                ),
                TextSpan(
                  text: 'Youv.ai',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the App.\n\nYour sole remedy for dissatisfaction with the App is to discontinue its use.\n\n',
                ),
                TextSpan(
                  text: '9. Intellectual Property\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'All software, content, logos, trademarks, and AI technology used in the App are owned by or licensed to Youv.ai.\n\nYou may not copy, modify, distribute, or exploit any part of the App without prior written permission.\n\n',
                ),
                TextSpan(
                  text: '10. Termination\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'We reserve the right to suspend or terminate your access to the App at any time if you violate these Terms.\n\nYou may stop using the App at any time by uninstalling it.\n\n',
                ),
                TextSpan(
                  text: '11. Changes to Terms\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'We may update these Terms from time to time.\n\nContinued use of the App after changes means you accept the revised Terms.\n\n',
                ),
                TextSpan(
                  text: '12. Governing Law\n\n',
                  style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: 'These Terms shall be governed by and construed in accordance with the laws of ',
                ),
                TextSpan(
                  text: 'India',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: '.',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}