import 'package:flutter/material.dart';

class TermsConditionsScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Terms and Conditions'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: SingleChildScrollView(
          child: RichText(
            text: TextSpan(
              style: TextStyle(fontSize: 16, color: Colors.black),
              children: [
                TextSpan(
                  text: '# Terms and Conditions\n\n',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                // TextSpan(
                //   text: 'Effective Date: ',
                // ),
                // TextSpan(
                //   text: '[Insert Date]',
                //   style: TextStyle(fontWeight: FontWeight.bold),
                // ),
                // TextSpan(
                //   text: '\nLast Updated: ',
                // ),
                // TextSpan(
                //   text: '[Insert Date]',
                //   style: TextStyle(fontWeight: FontWeight.bold),
                // ),
                TextSpan(
                  text: '\n\nWelcome to ',
                ),
                TextSpan(
                  text: 'Youv.ai',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' ("App", "we", "our", "us"). By using our app, you ("user", "you", "your") agree to the following Terms and Conditions. Please read them carefully before using our services. If you do not agree, you should not use the App.\n\n---\n\n## 1. Purpose of the App\n\n• The ',
                ),
                TextSpan(
                  text: 'Youv.ai App',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' provides ',
                ),
                TextSpan(
                  text: 'AI-based skin analysis',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' and related insights for ',
                ),
                TextSpan(
                  text: 'educational and informational purposes only',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: '.\n• The results, images, or recommendations generated are ',
                ),
                TextSpan(
                  text: 'not medical advice',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ', diagnosis, or treatment.\n• Always consult a licensed dermatologist or healthcare professional for any medical concerns.\n\n---\n\n## 2. Eligibility\n\n• You must be at least ',
                ),
                TextSpan(
                  text: '18 years old',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' (or have parental/guardian consent if under 18) to use this App.\n• By using the App, you confirm that all information you provide is accurate and truthful.\n\n---\n\n## 3. Use of AI-Generated Content\n\n• All ',
                ),
                TextSpan(
                  text: 'analysis, reports, and visual outputs',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' (including "before/after" simulations) are generated by AI and may not fully reflect actual results.\n• The App ',
                ),
                TextSpan(
                  text: 'does not guarantee accuracy',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' of the analysis or results.\n• AI-generated outputs should not be considered a substitute for professional medical consultation.\n\n---\n\n## 4. User Responsibilities\n\nYou agree:\n\n• To use the App for personal and non-commercial purposes only.\n• Not to misuse, copy, or resell AI outputs without our written consent.\n• To upload only your own images (or images you have the right to use).\n• Not to upload offensive, unlawful, or harmful content.\n\n---\n\n## 5. Privacy & Data Usage\n\n• We may collect and process personal data (including images) for the purpose of providing AI skin analysis.\n• Images uploaded may be temporarily stored and processed by our AI system.\n• We do not sell your personal information to third parties.\n• Please review our ',
                ),
                TextSpan(
                  text: 'Privacy Policy',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' for detailed information on data handling.\n\n---\n\n## 6. Payments & Subscriptions (If Applicable)\n\n• Some features may require a subscription or one-time payment.\n• All fees are displayed within the App before purchase.\n• Payments are handled securely through third-party payment providers.\n\n---\n\n## 7. Disclaimers\n\n• The App and its AI features are provided ',
                ),
                TextSpan(
                  text: '"as is" and "as available"',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' without any warranties.\n• We make no guarantees about accuracy, reliability, or results from using the App.\n• We are not responsible for decisions you make based on AI outputs.\n\n---\n\n## 8. Limitation of Liability\n\n• To the fullest extent permitted by law, ',
                ),
                TextSpan(
                  text: 'Youv.ai',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: ' shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the App.\n• Your sole remedy for dissatisfaction with the App is to discontinue use.\n\n---\n\n## 9. Intellectual Property\n\n• All software, logos, trademarks, and AI technology used in the App are owned by or licensed to Youv.ai.\n• You may not copy, modify, distribute, or exploit our content without prior permission.\n\n---\n\n## 10. Termination\n\n• We may suspend or terminate your access to the App at any time for violating these Terms.\n• You may stop using the App at any time by uninstalling it.\n\n---\n\n## 11. Changes to Terms\n\n• We may update these Terms from time to time.\n• Continued use of the App after changes means you accept the updated Terms.\n\n---\n\n## 12. Governing Law\n\n• These Terms shall be governed by and interpreted in accordance with the laws of ',
                ),
                TextSpan(
                  text: '[Insert Country/State]',
                  style: TextStyle(fontWeight: FontWeight.bold),
                ),
                TextSpan(
                  text: '.',
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}